SonyStore/Areas/Dashboard/Models/PhoneViewModel.cs
using SonyStore.Core.DAL.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SonyStore.Areas.Dashboard.Models
{
    public class PhoneViewModel : Model<Phone>
    {
        [Required(ErrorMessage = "Nomini kiriting")]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [Display(Name = "Rasm")]
        public HttpPostedFileBase Photo { get; set; }

        public string Path { get; set; }

        public string CategoryName { get; set; }

        [Required(ErrorMessage = "Categoriyani tanlang")]
        public int CategoryId { get; set; }

        [Required(ErrorMessage = "Narxini Kiriting")]
        public decimal Price { get; set; }

    }
}

SonyStore/Areas/Dashboard/Controllers/PhoneController.cs
using SonyStore.App_Start;
using SonyStore.Areas.Dashboard.Models;
using SonyStore.Core.BLL.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SonyStore.Areas.Dashboard.Controllers
{
    public class PhoneController : Controller
    {
        public ApplicationUserManager UserService { get { return ApplicationUserManager.Instance; } }
        public PhoneService PService { get { return PhoneService.Instance; } }

        // GET: Dashboard/Phone
        public ActionResult Index()
        {
            var query = PService.AllAsQuerable.AsEnumerable();
            var models = new List<PhoneViewModel>();

            foreach (var ent in query)
            {
                var model = new PhoneViewModel();
                model.LoadEntity(ent);
                models.Add(model);
            }


            return View(models);
        }

        // GET: Dashboard/Phone/Details/5
        public ActionResult Details(int id)
        {
            var type = PService.ById(id);
            var model = new PhoneViewModel();
            model.LoadEntity(type);
            return View(model);
        }

        // GET: Dashboard/Phone/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Dashboard/Phone/Create
        [HttpPost]
        public ActionResult Create(PhoneViewModel model)
        {
            if (ModelState.IsValid)
            {
                var product = model.CreateEntity();

                var newName = "";
                if (model.Photo != null)
                {
                    var ext = GetFileExtention(model.Photo.FileName);
                    newName = Guid.NewGuid().ToString() + ext;
                    var fileName = Server.MapPath(AppSettings.UploadDir + newName);
                    model.Photo.SaveAs(fileName);
                }
                else
                {
                    newName = "DefaultPhoto.jpg";
                    var fileName = Server.MapPath(AppSettings.UploadDir + newName);
                    model.Path = fileName;
                }

                PService.Create(product);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET: Dashboard/Phone/Edit/5
        public ActionResult Edit(int id)
        {
            var ent = PService.ById(id);
            var model = new PhoneViewModel();
            model.LoadEntity(ent);
            return View(model);
        }

        // POST: Dashboard/Phone/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, PhoneViewModel model)
        {
            if (ModelState.IsValid)
            {
                var product = PService.ById(model.Id);
                product = model.UpdateEntity(product);
                if (model.Photo != null)
                {
                    var fileName = Server.MapPath(AppSettings.UploadDir + product.Path);
                    if (System.IO.File.Exists(fileName))
                    {
                        System.IO.File.Delete(fileName);
                    }
                    var ext = GetFileExtention(model.Photo.FileName);
                    var newName = Guid.NewGuid().ToString() + ext;
                    fileName = Server.MapPath(AppSettings.UploadDir + newName);
                    model.Photo.SaveAs(fileName);
                    product.Path = newName;
                }

                PService.Update(product);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [NonAction]
        private string GetFileExtention(string FileName)
        {
            var i = FileName.LastIndexOf(".");
            if (i != -1)
            {
                return FileName.Substring(i);
            }
            return "";
        }

        // GET: Dashboard/Phone/Delete/5
        public ActionResult Delete(int id)
        {
            var product = PService.ById(id);
            if (product == null)
                return RedirectToAction("Index");
            var model = new PhoneViewModel();
            model.LoadEntity(product);
            return View(model);
        }

        // POST: Dashboard/Phone/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                PService.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SonyStore/Controllers/PhoneController.cs
using SonyStore.Areas.Dashboard.Models;
using SonyStore.Core.BLL.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SonyStore.Controllers
{
    public class PhoneController : Controller
    {
        public ApplicationUserManager UserService { get { return ApplicationUserManager.Instance; } }
        public PhoneService PService { get { return PhoneService.Instance; } }

        // GET: Dashboard/Phone
        public ActionResult Index()
        {
            var query = PService.AllAsQuerable.AsEnumerable();
            var models = new List<PhoneViewModel>();

            foreach (var ent in query)
            {
                var model = new PhoneViewModel();
                model.LoadEntity(ent);
                models.Add(model);
            }


            return View(models);
        }

        // GET: Dashboard/Phone/Details/5
        public ActionResult Phone(int id)
        {
            var type = PService.ById(id);
            var model = new PhoneViewModel();
            model.LoadEntity(type);
            return View(model);
        }
    }
}

SonyStore/Areas/Dashboard/Views/Phone/Create.cshtml
@model SonyStore.Areas.Dashboard.Models.PhoneViewModel

@{
    ViewBag.Title = "Create";
    var categoryService = SonyStore.Core.BLL.Services.CategoryService.Instance;
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Phone", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="File" accept="image/*" />
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryId, categoryService.GetSelectList(), "Albumni tanlang", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<dir class="w3-btn w3-ripple">
    @Html.ActionLink("Back to List", "Index")
</dir>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SonyStore/Areas/Dashboard/Views/Phone/Delete.cshtml
@model SonyStore.Areas.Dashboard.Models.PhoneViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <dir class="w3-btn w3-ripple">
                @Html.ActionLink("Back to List", "Index")
            </dir>
        </div>
    }
</div>

SonyStore/Areas/Dashboard/Views/Phone/Details.cshtml
@model SonyStore.Areas.Dashboard.Models.PhoneViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>
</div>
<p>
    <dir class="w3-btn w3-ripple">
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
    </dir>
    <dir class="w3-btn w3-ripple">
        @Html.ActionLink("Back to List", "Index")
    </dir>
</p>

SonyStore/Areas/Dashboard/Views/Phone/Edit.cshtml
@model SonyStore.Areas.Dashboard.Models.PhoneViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                <input type="file" name="Photo" accept="image/*" />
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<a class="w3-btn w3-ripple">
    @Html.ActionLink("Back to List", "Index")
</a>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SonyStore/Areas/Dashboard/Views/Phone/Index.cshtml
@model IEnumerable<SonyStore.Areas.Dashboard.Models.PhoneViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<style>
    #photo{
        border: 1px solid #ddd;
        border-radius: 4px;
        padding: 5px;
        width: 150px;
        height: 180px;
    }
</style>

<button class="w3-btn w3-round-large">@Html.ActionLink("Create now", "Create")</button>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <img id="photo" src="~/Content/PhonePhoto/@item.Path" alt="@item.Path"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            <dir class="w3-btn w3-ripple">
                @Html.ActionLink("Edit", "Edit", new { id = item.Id })
            </dir>
            <dir class="w3-btn w3-ripple w3-red">
                @Html.ActionLink("Details", "Details", new { id = item.Id })
            </dir>
            <dir class="w3-btn w3-ripple w3-yellow">
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </dir>
        </td>
    </tr>
}

</table>